// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pSGwZDAYME5TdPFpDRZPiX
// Component: EUURMtEcXj
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: pNUvmoFVnhKnbn/component

import { useScreenVariants as useScreenVariantsbfGvTWkOjKs55Y } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BfGvTWkOJKs55Y/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_origin.module.css"; // plasmic-import: pSGwZDAYME5TdPFpDRZPiX/projectcss
import sty from "./PlasmicNewPage.module.css"; // plasmic-import: EUURMtEcXj/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: p5zclV-1E8es/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: p1gUg2FqR_LCK/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: iP4LXwPvMVFQw/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: WJJNxzgspxnjB/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: NEfwK6-JY3fnG/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: PI-acuq_zg6/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: D1Qvzqhw3Cw_l/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: OiJhhWvfQ9K/icon

export type PlasmicNewPage__VariantMembers = {};

export type PlasmicNewPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewPage__VariantsArgs;
export const PlasmicNewPage__VariantProps = new Array<VariantPropType>();

export type PlasmicNewPage__ArgsType = {};
type ArgPropType = keyof PlasmicNewPage__ArgsType;
export const PlasmicNewPage__ArgProps = new Array<ArgPropType>();

export type PlasmicNewPage__OverridesType = {
  root?: p.Flex<"div">;
  container?: p.Flex<"div">;
  row?: p.Flex<"div">;
  headerLeft?: p.Flex<"a"> & Partial<LinkProps>;
  headerRight?: p.Flex<"div">;
  pageBanerSection?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  foreground?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
};

export interface DefaultNewPageProps {}

function PlasmicNewPage__RenderFunc(props: {
  variants: PlasmicNewPage__VariantsArgs;
  args: PlasmicNewPage__ArgsType;
  overrides: PlasmicNewPage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbfGvTWkOjKs55Y()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xqVvF)}>
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <div
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                className={classNames(projectcss.all, sty.row)}
              >
                <div className={classNames(projectcss.all, sty.column___7Bs5)}>
                  <p.PlasmicLink
                    data-plasmic-name={"headerLeft"}
                    data-plasmic-override={overrides.headerLeft}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.headerLeft
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___0KIqc)}
                      displayHeight={"67px" as const}
                      displayMaxHeight={"74px" as const}
                      displayMaxWidth={"199px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/origin/images/image.svg",
                        fullWidth: 300,
                        fullHeight: 113,
                        aspectRatio: 2.662651
                      }}
                    />
                  </p.PlasmicLink>
                </div>

                <div className={classNames(projectcss.all, sty.column__lG6Ok)}>
                  <div
                    data-plasmic-name={"headerRight"}
                    data-plasmic-override={overrides.headerRight}
                    className={classNames(projectcss.all, sty.headerRight)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__cmV0E
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Services"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___6O1Fj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Stories"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__qxyNh
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"About us"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__aw94K
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Contact us"}
                    </p.PlasmicLink>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__eiMZm)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Services"}
              </h1>
            </div>
          </div>

          <section className={classNames(projectcss.all, sty.section___8FMeu)}>
            <div className={classNames(projectcss.all, sty.freeBox__mt5Ky)}>
              <div className={classNames(projectcss.all, sty.freeBox__is8L)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oymn7)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__jHn6M)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__o2Qj)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jnbyc
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___7Ny7H
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___8MxS3
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tG9Eo
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__tqoG
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__t1CN5
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jFb3A
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__ptPi)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ftLax
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__b03Tc
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xmt2
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lMOas
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__i9ZL5
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__jqXlY
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kd4Ej
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__w2Ra7
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___6MsQ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__cg19W
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xfMeg
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___2Bs3E
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__hOebt
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___76VNy
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__puJil
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__bq0Y)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__greYc
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__mRu37
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__g9TWf
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oSkfx
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__wgDnu
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__bmouR
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gn7B
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__eGvUw
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__n8Cw4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___2Qs6F
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___2Yl4
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nlwbV
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__bpKxV
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___1K6Xq
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uIukn
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__kkrA1
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vpe4G
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__i6O7
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___2YEE
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ebioj
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__mHsYc
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__prIlz
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__g0T3C
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__goN)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__bhm0I
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "Why Choose Us"
                : "Our process"}
            </h2>

            <div className={classNames(projectcss.all, sty.freeBox__iey1D)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__fsAi3)}
              >
                <div className={classNames(projectcss.all, sty.column__fZwV)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1EXuH)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kmjGt)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg___73WUs)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__g2CCs)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__daT6K
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__fWfJ
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dDew9
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__wjk1G)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jtYfw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jedn8)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg___3A7H)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__adWhe)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__qLik8
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__oLx29
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xpPc9
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__kemq4)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__h0SYu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__w4JaZ)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg__kEbCl)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__iglHk)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__uVkrA
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__bQt9C
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__igYf7
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__yv98J)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cRiU)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xmq1J)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg__sdXSr)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__mqJzv)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__fz8Tn
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__qZ1IU
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9K30N
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__ohgmy)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__o1K1A)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dyp9)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg__ir6V9)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vbh9M)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__c1Nv
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__caiDi
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jq2JM
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__aChi)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qfaDq)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pGrkr)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg__bFCg9)}
                        role={"img"}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__b2RD)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          sty.h3__c2KAd
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___5Alor
                          )}
                        >
                          {"Services main"}
                        </h3>
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iZ30P
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                        }
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__z5Z6V)}>
            <div className={classNames(projectcss.all, sty.freeBox__lakao)}>
              <div className={classNames(projectcss.all, sty.freeBox__af84W)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__izCxu)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__sznr9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__c5ZMp
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uMpJ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___93ZLm
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__fgTpr
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___51B7
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__y2GKp
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__dbjKr
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___3Kr3A
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___581Gg
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kYjjg
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ljFjv
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vqH
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__opLh4
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__riNib
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__lbTw
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vRgJ
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__bTqOr
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___3CcJs
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fuy38
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__fF8Pd
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__i4K70
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__xgIrg
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__jJQ
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xSh7K
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__gAM)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r2V91
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ajBze
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___5IPga
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__b7Fl8
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__amovh
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__qnVna
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nbF3I
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9BuYv
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ufrCj
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aGi9Q
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__zoeRi
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qw5ZD
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3___5P0O
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___9UvGf
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__v6Me
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9KQqb
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__h9IUw
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wgf7T
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__n0LfP
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rLqsB
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                sty.h3__vbOjc
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__lcmeS
                                )}
                              >
                                {"Services main"}
                              </h3>
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uZysk
                              )}
                            >
                              {
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__hdIsF)}>
            <div className={classNames(projectcss.all, sty.freeBox__bl8Lj)}>
              <div className={classNames(projectcss.all, sty.freeBox__rMvd8)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jt2In)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__w0HTr)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hrKch
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__c1U13)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/origin/images/image2.jpeg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___7Igxc
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__u3VpZ
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__gnmdj
                            )}
                          >
                            {"Why Choose Us"}
                          </h2>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dNff
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                            }
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.columns__kk4Fj
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__zr0Md
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__t8K6G
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__ui2Vj
                                  )}
                                >
                                  <Icon8Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__yszU6
                                    )}
                                    role={"img"}
                                  />
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox___5K2Mi
                                  )}
                                >
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      sty.h3__wjfZg
                                    )}
                                  >
                                    <h3
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h3,
                                        projectcss.__wab_text,
                                        sty.h3__n06Ak
                                      )}
                                    >
                                      {"Services main"}
                                    </h3>
                                  </h3>

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__x5Auu
                                    )}
                                  >
                                    {
                                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                                    }
                                  </div>
                                </p.Stack>
                              </p.Stack>
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column___1Wj80
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ed1Dx
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__cd1IE
                                  )}
                                >
                                  <Icon8Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___3KwJa
                                    )}
                                    role={"img"}
                                  />
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__ktx62
                                  )}
                                >
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      sty.h3__yLFo
                                    )}
                                  >
                                    <h3
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h3,
                                        projectcss.__wab_text,
                                        sty.h3__syNQ
                                      )}
                                    >
                                      {"Services main"}
                                    </h3>
                                  </h3>

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__qoH6W
                                    )}
                                  >
                                    {
                                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                                    }
                                  </div>
                                </p.Stack>
                              </p.Stack>
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__sgClK
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ta2Pd
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__opciF
                                  )}
                                >
                                  <Icon8Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__cRdXx
                                    )}
                                    role={"img"}
                                  />
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox___6DTx6
                                  )}
                                >
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      sty.h3__kMcca
                                    )}
                                  >
                                    <h3
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h3,
                                        projectcss.__wab_text,
                                        sty.h3__rje05
                                      )}
                                    >
                                      {"Services main"}
                                    </h3>
                                  </h3>

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__k7M68
                                    )}
                                  >
                                    {
                                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                                    }
                                  </div>
                                </p.Stack>
                              </p.Stack>
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__kR64R
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___8RIw8
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__paWeR
                                  )}
                                >
                                  <Icon8Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__zaGox
                                    )}
                                    role={"img"}
                                  />
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__sbQ8G
                                  )}
                                >
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      sty.h3__zHp6L
                                    )}
                                  >
                                    <h3
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h3,
                                        projectcss.__wab_text,
                                        sty.h3__hxFhq
                                      )}
                                    >
                                      {"Services main"}
                                    </h3>
                                  </h3>

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__sbjA5
                                    )}
                                  >
                                    {
                                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                                    }
                                  </div>
                                </p.Stack>
                              </p.Stack>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <div className={classNames(projectcss.all, sty.freeBox__p3MKd)}>
            <div className={classNames(projectcss.all, sty.freeBox__fc8Hj)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__z4Okq)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7NR0R)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mtTKy)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__k0ODf
                      )}
                    >
                      {"Company Name"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n4ND
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"This site proudly built in "}
                        </React.Fragment>
                        {
                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.link__gxAsr
                            )}
                            component={Link}
                            href={"https://www.plasmic.app" as const}
                            platform={"nextjs"}
                          >
                            {"Plasmic"}
                          </p.PlasmicLink>
                        }
                        <React.Fragment>{"."}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gvazo
                      )}
                    >
                      {"Connect with us"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__mf18A)}
                    >
                      {true ? (
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link___0MVVt
                          )}
                          component={Link}
                          href={"#" as const}
                          platform={"nextjs"}
                          target={"_blank" as const}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gUwcL
                            )}
                            role={"img"}
                          />
                        </p.PlasmicLink>
                      ) : null}
                      {true ? (
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__wgo0R
                          )}
                          component={Link}
                          href={"#" as const}
                          platform={"nextjs"}
                          target={"_blank" as const}
                        >
                          <Icon2Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__am9Q
                            )}
                            role={"img"}
                          />
                        </p.PlasmicLink>
                      ) : null}
                      {true ? (
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link___2CzzN
                          )}
                          component={Link}
                          href={"#" as const}
                          platform={"nextjs"}
                          target={"_blank" as const}
                        >
                          <Icon28Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___82LsA
                            )}
                            role={"img"}
                          />
                        </p.PlasmicLink>
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fkmF2)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__crwwq
                    )}
                  >
                    {"Photography"}
                  </h3>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___2F97K
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__lo7Gb)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hfy4T
                      )}
                    >
                      {"Services"}
                    </div>

                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__zp39X)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__tqoni
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__pUrY)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hAyln
                      )}
                    >
                      {"Stories"}
                    </div>

                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__th7AC)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__mNiiz)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__vHa0X
                    )}
                  >
                    {"Company"}
                  </h3>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__xk1Il
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__pFxOh)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pcVdj
                      )}
                    >
                      {"Contact us"}
                    </div>

                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__rtC0)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___906TA
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__uGmD)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nrUuW
                      )}
                    >
                      {"About us"}
                    </div>

                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__dd60)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(projectcss.all, sty.section__fZySd)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground)}
            >
              <div className={classNames(projectcss.all, sty.column__kI0No)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7XWga)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lhIiv
                    )}
                  >
                    {"Freedoms"}
                  </div>

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___3Kavc
                    )}
                  >
                    {"Open by design"}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oug2A
                    )}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>

                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    endIcon={
                      <Icon17Icon
                        className={classNames(projectcss.all, sty.svg__cmWdq)}
                        role={"img"}
                      />
                    }
                    showEndIcon={true}
                    size={"minimal" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lhIn
                      )}
                    >
                      {"Learn more"}
                    </div>
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__aEaD7)}>
                <div className={classNames(projectcss.all, sty.freeBox__i25Sq)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lJdNu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3ROfo
                      )}
                    >
                      {"Built on capability"}
                    </div>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__rNyc2)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__iamrz)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__keVo
                      )}
                    >
                      {"Highly energetic"}
                    </div>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__d2Nsr)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__my7Ht)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__epEcz
                      )}
                    >
                      {"100% transparency and accountability"}
                    </div>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__buvi8)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lqNq3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vcjcF
                      )}
                    >
                      {"Refreshing clarity"}
                    </div>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__qujtz)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mhTj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iaGe
                      )}
                    >
                      {"Modern results"}
                    </div>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg___40Ka)}
                      role={"img"}
                    />
                  </p.Stack>
                </div>
              </div>
            </p.Stack>
          </p.Stack>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "container",
    "row",
    "headerLeft",
    "headerRight",
    "pageBanerSection",
    "h1",
    "foreground",
    "button"
  ],
  container: ["container", "row", "headerLeft", "headerRight"],
  row: ["row", "headerLeft", "headerRight"],
  headerLeft: ["headerLeft"],
  headerRight: ["headerRight"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  foreground: ["foreground", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  container: "div";
  row: "div";
  headerLeft: "a";
  headerRight: "div";
  pageBanerSection: "div";
  h1: "h1";
  foreground: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewPage__VariantsArgs;
    args?: PlasmicNewPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNewPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNewPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNewPage__ArgProps,
          internalVariantPropNames: PlasmicNewPage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicNewPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage";
  } else {
    func.displayName = `PlasmicNewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage = Object.assign(
  // Top-level PlasmicNewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    row: makeNodeComponent("row"),
    headerLeft: makeNodeComponent("headerLeft"),
    headerRight: makeNodeComponent("headerRight"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    foreground: makeNodeComponent("foreground"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicNewPage
    internalVariantProps: PlasmicNewPage__VariantProps,
    internalArgProps: PlasmicNewPage__ArgProps
  }
);

export default PlasmicNewPage;
/* prettier-ignore-end */
